#!/usr/bin/env bash
#
# Renders the Homebrew formula for langazov/homebrew-tap from a release's
# checksum file.
#
# The tap ships a *formula*, not a cask, for two reasons: casks are macOS-only
# (Homebrew on Linux ignores them), and casks quarantine what they download.
# These binaries are unsigned, so a cask install would be blocked by Gatekeeper
# until the user cleared the xattr by hand. Formula downloads are not
# quarantined.
#
# One formula ships all three binaries, because two of them exist only to serve
# the first:
#
#   bin/gocode              the agent
#   bin/mdlsp               the markdown language server, started by gocode for
#                           .md files and usable by any LSP-speaking editor
#   libexec/rag-plugin/     the semantic-search process plugin: binary plus the
#                           gocode-plugin.json manifest the loader needs
#
# Installing is not enabling: a plugin runs only when the config's `plugin`
# array names it, and a server under libexec is not on PATH for the registry to
# find. post_install closes both gaps by calling the binary's own config
# editor, so `brew install` leaves a working setup rather than a pile of files
# and a paragraph of instructions.
#
# Usage:
#   script/brew-formula.sh <version> <sha256sums-file> [output]
#
# <sha256sums-file> is the SHA256SUMS asset from the release: lines of
# "<sha256>  gocode-<version>-<platform>[.tar.gz]". Only the .tar.gz entries
# are used; the bare-executable entries are ignored.
#
# With no [output] the formula is written to stdout.
set -euo pipefail

version="${1:?usage: brew-formula.sh <version> <sha256sums-file> [output]}"
sums="${2:?usage: brew-formula.sh <version> <sha256sums-file> [output]}"
output="${3:-}"

# Pull the checksum for one archive out of the sums file. Fails loudly rather
# than emitting a formula with a blank sha256, which Homebrew would only
# reject at install time on the user's machine.
sha_for() {
  local platform="$1"
  local archive="gocode-${version}-${platform}.tar.gz"
  local sha
  sha="$(awk -v want="$archive" '$2 == want || $2 == "*" want { print $1; exit }' "$sums")"
  if [ -z "$sha" ]; then
    echo "no checksum for $archive in $sums" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

macos_arm64="$(sha_for macos-arm64)"
macos_x64="$(sha_for macos-x64)"
linux_arm64="$(sha_for linux-arm64)"
linux_x64="$(sha_for linux-x64)"

render() {
  cat <<EOF
# This file is generated by script/brew-formula.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
class Gocode < Formula
  desc "Terminal-based AI coding agent"
  homepage "https://github.com/langazov/gocode"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-macos-arm64.tar.gz"
      sha256 "${macos_arm64}"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-macos-x64.tar.gz"
      sha256 "${macos_x64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-linux-arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-linux-x64.tar.gz"
      sha256 "${linux_x64}"
    end
  end

  def install
    bin.install "gocode"
    # A general LSP server, not a gocode internal: editors are pointed at it
    # directly, and gocode's own registry finds it by name on PATH.
    bin.install "mdlsp"
    # The plugin stays out of PATH — it is not a command anyone runs — but
    # keeps its directory layout, since the loader resolves a plugin by
    # reading gocode-plugin.json next to the binary.
    libexec.install "rag-plugin"
  end

  # Wire both extras into the user's global config. Homebrew runs this as the
  # user, so it reaches ~/.config/gocode; the edits are idempotent, preserve
  # every other key, and refuse to rewrite a config carrying comments.
  #
  # opt_ paths are used rather than the versioned Cellar path so an upgrade
  # does not leave the config pointing at a directory that no longer exists.
  #
  # A failure here is warned about, not raised: the binaries are installed and
  # usable either way, and a config this cannot parse is a reason to tell the
  # user rather than to fail their upgrade.
  def post_install
    [
      ["lsp", "enable", "mdlsp",
       "--global", "--command", opt_bin/"mdlsp", "--extensions", ".md,.markdown"],
      ["plugin", "enable", (opt_libexec/"rag-plugin").to_s,
       "--global", "--options", '{"embeddingProvider":"openai"}'],
    ].each do |args|
      system bin/"gocode", *args
    rescue StandardError => e
      opoo "could not run 'gocode #{args[0]} #{args[1]}': #{e}"
      opoo "Wire it up by hand; 'brew info gocode' lists the commands."
    end
  end

  def caveats
    <<~EOS
      Two extras were installed alongside gocode and wired into
      ~/.config/gocode:

        mdlsp       markdown language server, started for .md files
        rag-plugin  semantic code search (rag_index / rag_search tools)

      rag-plugin embeds through an OpenAI-compatible endpoint, so it needs a
      credential before its tools will work:

        gocode auth login

      To turn either off again (the files stay installed):

        gocode lsp disable mdlsp
        gocode plugin disable #{opt_libexec}/rag-plugin
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gocode --version")
    assert_match "mdlsp", shell_output("#{bin}/mdlsp --version")
    # The manifest is what makes the directory loadable as a plugin.
    assert_predicate libexec/"rag-plugin/gocode-plugin.json", :exist?
  end
end
EOF
}

# Ruby's #{...} interpolations survive this script's heredoc untouched: bash
# expands $-prefixed forms, and #{ is not one. Only ${...} would need escaping,
# and the formula uses none.
if [ -n "$output" ]; then
  mkdir -p "$(dirname "$output")"
  render > "$output"
  echo "wrote $output" >&2
else
  render
fi
