#!/usr/bin/env bash
#
# Renders the Homebrew formula for langazov/homebrew-tap from a release's
# checksum file.
#
# The tap ships a *formula*, not a cask, for two reasons: casks are macOS-only
# (Homebrew on Linux ignores them), and casks quarantine what they download.
# These binaries are unsigned, so a cask install would be blocked by Gatekeeper
# until the user cleared the xattr by hand. Formula downloads are not
# quarantined.
#
# Usage:
#   script/brew-formula.sh <version> <sha256sums-file> [output]
#
# <sha256sums-file> is the SHA256SUMS asset from the release: lines of
# "<sha256>  gocode-<version>-<platform>[.tar.gz]". Only the .tar.gz entries
# are used; the bare-executable entries are ignored.
#
# With no [output] the formula is written to stdout.
set -euo pipefail

version="${1:?usage: brew-formula.sh <version> <sha256sums-file> [output]}"
sums="${2:?usage: brew-formula.sh <version> <sha256sums-file> [output]}"
output="${3:-}"

# Pull the checksum for one archive out of the sums file. Fails loudly rather
# than emitting a formula with a blank sha256, which Homebrew would only
# reject at install time on the user's machine.
sha_for() {
  local platform="$1"
  local archive="gocode-${version}-${platform}.tar.gz"
  local sha
  sha="$(awk -v want="$archive" '$2 == want || $2 == "*" want { print $1; exit }' "$sums")"
  if [ -z "$sha" ]; then
    echo "no checksum for $archive in $sums" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

macos_arm64="$(sha_for macos-arm64)"
macos_x64="$(sha_for macos-x64)"
linux_arm64="$(sha_for linux-arm64)"
linux_x64="$(sha_for linux-x64)"

render() {
  cat <<EOF
# This file is generated by script/brew-formula.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
class Gocode < Formula
  desc "Terminal-based AI coding agent"
  homepage "https://github.com/langazov/gocode"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-macos-arm64.tar.gz"
      sha256 "${macos_arm64}"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-macos-x64.tar.gz"
      sha256 "${macos_x64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-linux-arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "https://github.com/langazov/gocode/releases/download/v${version}/gocode-${version}-linux-x64.tar.gz"
      sha256 "${linux_x64}"
    end
  end

  def install
    bin.install "gocode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gocode --version")
  end
end
EOF
}

if [ -n "$output" ]; then
  mkdir -p "$(dirname "$output")"
  render > "$output"
  echo "wrote $output" >&2
else
  render
fi
