#!/usr/bin/env bash
#
# Renders the Homebrew cask for the gocode_gui desktop app, published to
# langazov/homebrew-tap next to the gocode formula (see brew-formula.sh).
#
# A cask rather than a formula because the artifact is a macOS .app bundle,
# which is what casks exist to install into /Applications. That also makes it
# macOS-only; the Linux and Windows builds stay on the GitHub release.
#
# The app is only a client: it spawns `gocode serve` in the project folder the
# user picks. So the cask depends on the gocode formula, and the app finds the
# binary through the login-shell PATH, which includes Homebrew's prefix.
#
# Usage:
#   script/brew-cask.sh <version> <sha256sums-file> [output]
#
# <sha256sums-file> is the release's SHA256SUMS; only the
# gocode-desktop-<version>-macos-universal.zip line is used.
#
# With no [output] the cask is written to stdout.
set -euo pipefail

version="${1:?usage: brew-cask.sh <version> <sha256sums-file> [output]}"
sums="${2:?usage: brew-cask.sh <version> <sha256sums-file> [output]}"
output="${3:-}"

# Fail loudly rather than publish a cask with a blank sha256, which Homebrew
# would only reject at install time on the user's machine.
archive="gocode-desktop-${version}-macos-universal.zip"
sha="$(awk -v want="$archive" '$2 == want || $2 == "*" want { print $1; exit }' "$sums")"
if [ -z "$sha" ]; then
  echo "no checksum for $archive in $sums" >&2
  exit 1
fi

# Ruby's #{...} interpolations pass through this heredoc untouched; only
# ${...} is expanded by bash. Keep backticks out of the template: bash would
# run them as command substitutions, even inside a Ruby comment.
render() {
  cat <<EOF
# This file is generated by script/brew-cask.sh in langazov/gocode.
# DO NOT EDIT; changes are overwritten on the next release.
cask "gocode-desktop" do
  version "${version}"
  sha256 "${sha}"

  url "https://github.com/langazov/gocode/releases/download/v#{version}/gocode-desktop-#{version}-macos-universal.zip"
  name "gocode"
  desc "Desktop client for the gocode AI coding agent"
  homepage "https://github.com/langazov/gocode"

  livecheck do
    skip "Updated by the gocode release workflow."
  end

  # The app runs "gocode serve" for the folder you open, so it needs the CLI.
  depends_on formula: "langazov/tap/gocode"
  depends_on macos: :monterey

  app "Gocode Desktop.app"

  # The app is not signed or notarized, and casks quarantine what they
  # download, so Gatekeeper would refuse to open it. Clearing the flag is what
  # the release notes otherwise ask users to do by hand. Remove this once the
  # release is signed with a Developer ID.
  #
  # A declarative step, as Homebrew 7 requires: {{appdir}} is expanded by
  # Homebrew at install time, and the step sandbox may write to the app dir.
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/Gocode Desktop.app"]
  end

  zap trash: [
    "~/Library/Application Support/dev.gocode.gocodeGui",
    "~/Library/Caches/dev.gocode.gocodeGui",
    "~/Library/Preferences/dev.gocode.gocodeGui.plist",
    "~/Library/Saved Application State/dev.gocode.gocodeGui.savedState",
  ]
end
EOF
}

if [ -n "$output" ]; then
  mkdir -p "$(dirname "$output")"
  render > "$output"
  echo "wrote $output" >&2
else
  render
fi
